---
title: Goodstuffv2
timezone: America/Regina
collections:
  3g3q:
    title: 3G3Q
    output: true
    permalink: "/3g3q/:path"
    slug: 3g3q
    retired: false
    live: false
  aux:
    title: Auxiliary
    output: true
    permalink: "/aux/:path"
    retired: false
    live: false
  dailyish:
    title: Daily(ish)
    output: true
    permalink: "/dailyish/:path"
    retired: false
    live: false
  specials:
    title: Goodstuff Specials
    output: true
    permalink: "/specials/:path"
    retired: false
    live: false
  grownups:
    title: I Guess We're Grown-Ups Now
    output: true
    permalink: "/grownups/:path"
    retired: false
    live: false
  ll:
    title: Lost & Lemon
    output: true
    permalink: "/ll/:path"
    retired: true
    live: false
  morningshow:
    title: Morning Show
    output: true
    permalink: "/morningshow/:path"
    retired: false
    live: false
  neverdigdown:
    title: Never Dig Down
    output: true
    permalink: "/neverdigdown/:path"
    retired: true
    live: false
  nbsp:
    title: Non Breaking Space Show
    output: true
    permalink: "/nbsp/:path"
    live: false
    retired: false
  people:
    title: People
    output: true
    permalink: "/people/:title"
  posts:
    title: Posts
    output: true
  smym:
    title: Show Me Your Mic
    output: true
    permalink: "/smym/:path"
    retired: true
    live: false
  atu2:
    title: The atU2 Podcast
    output: true
    permalink: "/atu2/:path"
    live: false
    retired: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: morningshow
  values:
    layout: episode
    mp3:
    episode:
    description:
    sponsor: FeedPress
    sponsor-link: http://feed.press/morningshow
    sponsor-copy: Hosting and feed support provided by Feed.Press. [Sign-up today](http://feed.press/morningshow)
      and try FeedPress on a 14 day trial (no contracts or commitments). Use promo
      code `morningshow` during checkout to get 10% off your first year.
    show: morningshow
- scope:
    path: ''
    type: 3g3q
  values:
    layout: episode
    mp3:
    episode:
    description:
    sponsor: Our fantastic patrons
    sponsor-link: http://www.patreon.com/3g3q
    sponsor-copy: Join them on Patreon to get access to exclusive bonus material, access to the StuffySlack, and other extras.
    show: 3g3q
include:
- _pages
itunes-subtitle: your-podcast-subtitle
itunes-url: http://goodstuff.fm
itunes-email: contact@goodstuff.fm
itunes-lang: EN
itunes-author: Goodstuff Broadcasting
permalink: pretty
Goodstuff Twitter: https://twitter.com/goodstufffm
logo-small: "/assets/logo-small.svg"
logo: "/assets/logo.svg"
description: The internet’s favorite shows on technology, culture, news, and more.
  You know, just the good stuff.
copyright: "© 2014–2016 Goodstuff Broadcasting"
sass:
  sass_dir: "./styles"
gems:
- jekyll-sitemap
