---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Podcasts
- type: directory
  path: _3g3q
  label: 3 Guys 3 Questions
  create: all
  match: "**/*"
  templates:
  - 3g3q-episode
- type: directory
  path: _baseline
  label: Baseline
  create: documents
  match: "**/*"
- type: directory
  path: _clockworks
  label: Clockworks
  create: documents
  match: "**/*"
  templates:
  - clockworks-episode
- type: directory
  path: _dailyish
  label: Dailyish
  create: documents
  match: "**/*"
  templates:
  - dailyish-episode
- type: directory
  path: _grownups
  label: Grownups
  create: all
  match: "**/*"
- type: directory
  path: _midnightsnack
  label: Midnight Snack
  create: all
  match: "**/*"
- type: directory
  path: _noidea
  label: No Idea
  create: all
  match: "**/*"
  templates:
  - no-idea-episode
- type: directory
  path: _smym
  label: Show Me Your Mic
  create: documents
  match: "**/*"
  templates:
  - smym-episode
- type: directory
  path: _wts
  label: Way Too Seriously
  create: documents
  match: "**/*"
  templates:
  - way-too-seriously-episode
- type: directory
  path: _atu2
  label: "@U2 Podcast"
  create: documents
  match: "**/*"
  templates:
  - u2-episode
- type: heading
  label: Content
- type: directory
  path: _people
  label: People
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: _uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
